# Colors (Alabaster)
# author tonsky

[colors.primary]
background = '#0e1415'
foreground = '#cecece'

[colors.cursor]
text = '#cecece'
cursor = '#434343'

[colors.normal]
black = "#333333"
blue = "#71aed7"
cyan = "#47bea9"
green = "#95cb82"
magenta = "#cc8bc9"
red = "#c33c33"
white = "#cecece"
yellow = "#cd974b"

[colors.bright]
black = "#333333"
blue = "#71aed7"
cyan = "#47bea9"
green = "#95cb82"
magenta = "#cc8bc9"
red = "#c33c33"
white = "#cecece"
yellow = "#cd974b"
